### ISSUE TITLE
Unhandled exception is not reported

### ISSUE THREAD

**Issue by GDreyV** [bugsnag/bugsnag-dotnet#107]
I'm creating uwp app and added unhandledException handler in app.xaml.cs which looks like:
```c#
var bugsnag = new Bugsnag.Client(new Bugsnag.Configuration("{APP_KEY}"));
bugsnag.Notify(e.Exception, Bugsnag.Severity.Error);
```
But there is no errors in bugsnag dashboard. Is there any way to debug the problem?
Bugsnag version is 2.1.0.

**Comment by martin308** [comment]
@GDreyV unfortunately we don't currently support UWP applications. I spun up a test application to see if it would work and the application will not start due to our use of the `System.Threading.Thread` package which is not supported on UWP. I'll add a ticket to our roadmap to look into supporting UWP

**Comment by GDreyV** [comment]
@martin308 thanks for update. Just want to add some details for future. Really I found that some error were sent correctly to bugsnag. It seems like in most cases application was closed before bugsnag managed to send data.
Also references to netstandard2 force to use most recent windows version and target.

**Comment by martin308** [comment]
@GDreyV thanks for the additional information 🙏 

Do you have a sample project that sends errors to Bugsnag? I couldn't get a basic UWP application to event start when initializing the bugsnag client as it tries to load the System.Threading dll which didn't exist.

The bugsnag nuget package does also have a netstandard13 implementation alongside netstandard2, is it not able to use that?

**Comment by GDreyV** [comment]
Really? I found that netstandard13 implementation is pretty old and available in version 1.
Here's the app to reproduce the problem: https://github.com/GDreyV/bugsnag-uwp-test

**Comment by martin308** [comment]
Thanks for putting that project together, I'll take a look as soon as I can!

I'm not sure what you mean in regards to the netstandard13 implementation. We only supported net35 and net45 in version 1 of the notifier. 

We [target](https://github.com/bugsnag/bugsnag-dotnet/blob/master/src/Bugsnag/Bugsnag.csproj#L6) the current code for net35, net45, netstandard13 and netstandard2. There is only minimal differences for the netstandard13 implementation where the required classes/functionality is not available. I'd love to get to the bottom of this if there is an issue with our nuget package

**Comment by GDreyV** [comment]
Maybe I'm doing something wrong but I'm using bugsnag version 2.1.0 (latest stable). If I change min target version to Build 15063 (which doesn't include netstandard2) and run the app with test call of Bugsnag.Notify I get error System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Threading.Thread, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.' As I understand Thread v.4 is part of netstandard2.
