### ISSUE TITLE
Thread-Safe?

### ISSUE THREAD

**Issue by spib** [bugsnag/bugsnag-dotnet#111]
Hi

Under certain cicumstances we've seen errors in being thrown in our app which look like an error in the BugSnag client.

    System.Threading.ThreadAbortException: Thread was being aborted.
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Bugsnag.Payload.PayloadExtensions.AddToPayload[T](Dictionary`2 dictionary, String key, T value)
       at idss.Global.SetupBugSnag()
       at idss.Global.Application_BeginRequest(Object sender, EventArgs e)

[Googling around](https://stackoverflow.com/questions/39923397/c-sharp-dictionary-lookup-throws-index-was-outside-the-bounds-of-the-array) it seems like this might be solved by using a ConcurrentDictionary rather than a Generic Dictionary.

Or should we be calling BugSnag in a different way?

**Comment by martin308** [comment]
@spib do you have any more details around what you are calling on Bugsnag to cause this? It would seem odd to have a threading issue based on your stack trace as there should only be a single thread handling each ASP.NET request, but the error message certainly suggests it!

**Comment by spib** [comment]
Nothing special, except that the busnag client itself is being created using a static/singleton pattern because it's used in a few different places in the code.

**Comment by martin308** [comment]
The bugsnag client is designed to use a single client per request in an ASP.NET application. There is a convenience method [here](https://github.com/bugsnag/bugsnag-dotnet/blob/master/src/Bugsnag.AspNet/Client.cs#L13) that you can use to access the current requests client. Does that help?
