### ISSUE TITLE
Bugsnag crashes WPF application

### ISSUE THREAD

**Issue by NikasZalias** [bugsnag/bugsnag-dotnet#131]
When installed the latest bugsnag version for WPF app. It crashes app, cause AppName.exe.config is not found. 

Previous versions didn't have this bug.

### Steps to reproduce
1. Create WPF app with bugsnag nuget installed and configure it.
2. Delete appname.exe.config file (cause it is not needed for app to run successfully.)
3. start the app and it will crash.

### Environment
* Bugsnag version: 2.2.1
* .NET framework version: .NET Framework 4.6.1

**Comment by mattdyoung** [comment]
Hi @NikasZalias 

WPF applications are not yet supported by the v2.x integration. The documentation recommends using v1.4.0:
https://docs.bugsnag.com/platforms/dotnet/wpf/

Can you confirm whether there's still an issue with WPF apps using v1.4.0, or with the latest on other types of .NET project?

**Comment by NikasZalias** [comment]
Hey @mattdyoung 

WPF app works fine with 2.2.0 version and below.

What is the ETA to make it compatible with WPF apps?

**Comment by mattdyoung** [comment]
We don't yet have an ETA for when we can add full WPF support in v2.x.

This does look like a potential issue with other types of .NET project as well though.

**Comment by yousif-bugsnag** [comment]
This is now fixed in [v2.2.2](https://github.com/bugsnag/bugsnag-dotnet/releases/tag/v2.2.2)
