### ISSUE TITLE
Support for AggregateException

### ISSUE THREAD

**Issue by xPaw** [bugsnag/bugsnag-dotnet#22]
Ref: https://msdn.microsoft.com/en-us/library/system.aggregateexception

Currently it gets logged as is, and it doesn't provide any useful information.

**Comment by CodeHex** [comment]
Seems there's a bug where inner exceptions aren't being displayed at all, just copies of the original exception.

Also the code doesn't handle multiple inner exceptions (in the case of AggregateExceptions where there have been multiple exceptions thrown when the exceptions are observed).

About to submit a pull request which should deal with both.

**Comment by snmaynard** [comment]
This has now been fixed!
