### ISSUE TITLE
.NET 3.5 support

### ISSUE THREAD

**Issue by ConradIrwin** [bugsnag/bugsnag-dotnet#25]
Install-Package : Could not install package 'Bugsnag 1.0.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

At line:1 char:1

+ Install-Package Bugsnag
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by ConradIrwin** [comment]
Potentially there's a solution in https://docs.nuget.org/Create/Enforced-Package-Conventions#supporting-multiple-.net-framework-versions-and-profiles.

**Comment by snmaynard** [comment]
Fix landed in master
