### ISSUE TITLE
Deal with offline crashes

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-dotnet#31]
We should cache them somewhere and send them later.

This is required for windows forms apps, windows phone and xamarin etc.

**Comment by marchello2000** [comment]
Do you guys have a timeline for this yet? Just curious, thanks!

**Comment by ConradIrwin** [comment]
It's not officially scheduled, but this is probably one of the more important issues open on this notifier. Hopefully soon, and sorry I can't be more specific.

**Comment by kattrali** [comment]
Fixed in #55
