### ISSUE TITLE
Notifier.Send can't leak exceptions

### ISSUE THREAD

**Issue by marchello2000** [bugsnag/bugsnag-dotnet#32]
Notifier.Send must be enclosed in a try/catch to never ever leak an exception (except maybe if the debugger is attached?) Basically, right now, if there is no network it will bring down the process.

Say, I have an event I want to notify (that's non fatal) I call Client.Notify() bug I have no network - crash.

**Comment by ConradIrwin** [comment]
This should be fixed by #33

**Comment by marchello2000** [comment]
Did you guys publish a new Nuget package for this yet?

**Comment by snmaynard** [comment]
Done - apologies for the delay!
