### ISSUE TITLE
ASP.NET 5 support

### ISSUE THREAD

**Issue by samritchie** [bugsnag/bugsnag-dotnet#34]
ASP.NET 5 includes substantial changes that the BugSnag notifier will need to be modified to support, including:
- all MVC-related types have moved to Microsoft.AspNet namespace; the exception handler filter will need to be modified to cater for these.
- ConfigurationSettingsHandlers are no longer used (no web.config, ideally), so setup/config should be done via an IApplicationBuilder extension method.
- it would be nice to also have an ILogger implementation and notify at certain log levels - not sure if this behaviour is in line with that provided on other platforms.

This will most likely need to be provided via a separate NuGet package; it may be a battle to try and support different MVC versions in the one assembly.

**Comment by jessicard** [comment]
Thanks @samritchie! :) This is a great list to consider for ASP.NET 5 support. We've got these on our list as well for an eventual update, but we are always accepting PRs in the meantime.

**Comment by jaredcnance** [comment]
Any update on this since .Net Core RTM?

**Comment by martin308** [comment]
@samritchie @jaredcnance I have just pushed v2 (alpha) of our .net notifier which support ASP.NET Core to Nuget. It is an alpha release right now but we would love to have any feedback on it https://www.nuget.org/packages/Bugsnag.AspNet.Core/
