### ISSUE TITLE
Create an NLog target

### ISSUE THREAD

**Issue by PureKrome** [bugsnag/bugsnag-dotnet#37]
Hi Team.

NLog is one of the most widely used logging frameworks in .NET today, superseding Log4Net. 

Could we please have an NLog target so we can have another option for logging to Bugsnag?

References: [LogEntries Targets](https://github.com/NLog/NLog/wiki/Targets) documentation.

Pro Tip: There's plenty of existing targets already coded for .NET, but for other companies. It's not hard to use those as references to get a target up and running really quick :+1:

**Comment by ConradIrwin** [comment]
See also #38  :).

**Comment by PureKrome** [comment]
![](http://i.giphy.com/AcfcFH8ix0qOI.gif)

![](https://camo.githubusercontent.com/4665c057745cb43258e6779c3504d4b6a253f656/687474703a2f2f692e696d6775722e636f6d2f314248655650622e706e67)

:+1: 

for the full gory code-details & install instructions (schema, etc) : [NLog BugSnag Repo on GitHub]( https://github.com/PureKrome/NLog.Bugsag)

Anyone @ BugSnag, care to try pwease? (all the info at that GH repo)...

**Comment by kattrali** [comment]
Well this is awesome, I'm not sure how it was overlooked. There was a typo in the repo link - fixed that and adding a link to the NLog notifier to the Bugsnag documentation. 🎉  We'd like to show our appreciation, so if you send an email to support@bugsnag.com, we'll send you a care package. Thanks!
