### ISSUE TITLE
Automatically detect stacktrace prefixes

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-dotnet#40]
There is a common problem where an app is being built on multiple developers machines, and the stacktrace file names differ due to this, eg:
- `c:\users\james\myapp.cs`
- `c:\users\simon\myapp.cs`

Is there a way to automatically detect the stacktrace prefix for an app? If so that would be awesome. 

Alternatively it would be great if we could allow regular expressions in `SetFilePrefix`.

**Comment by CodeHex** [comment]
Looks like TeamCity (and probably most build servers) will auto generate folders using a set pattern e.g. auto-generated build number in the file path. Having regular expressions allow us to cater to these types of builds

+1 regexs

**Comment by SergIlliukhin** [comment]
It would be very useful, thanks

**Comment by snmaynard** [comment]
This is actually a dup of #8 so closing this one. This is going to form a part of our next .net sprint
