### ISSUE TITLE
.Notify shouldn't require being on the UI thread

### ISSUE THREAD

**Issue by marchello2000** [bugsnag/bugsnag-dotnet#47]
Currently, `WPFClient` registers `BeforeNotify` handler which requires UI thread access just to get the window title for `error.Context`.

```
at Bugsnag.Clients.WPFClient.<.cctor>b__0(Event error) in c:\projects\bugsnag-dotnet\src\Bugsnag\Clients\WPFClient.cs:line 23
```

If `.Notify()` is called from non UI thread, reporting an exception will generate an exception (quite unfortunate).
Solution is to probably wrap it in `try/catch`. Also, suggest not even running this code if `error.Context` is already set by the client's `BeforeNotify`.

**Comment by martin308** [comment]
@marchello2000 we are in the process of rolling out v2 of this notifier. The initial release will not have WPF specific functionally but we will roll that out soon after and fix this issue
