### ISSUE TITLE
OWIN-based app in infinite `UnobservedTaskException` handler loop?

### ISSUE THREAD

**Issue by RPM1984** [bugsnag/bugsnag-dotnet#50]
Hey guys,

I recently upgraded my Nancy .NET app to run on OWIN/Katana.

All was fine, then all of a sudden in production after some load i the app was locked (no requests were being served), and i saw an influx of BugSnag errors (like 100s of 1000s in a matter of seconds):
![image](https://cloud.githubusercontent.com/assets/930343/12875737/ca896d12-ce44-11e5-8941-3ccbd59c9dba.png)

From my understanding, this basically means the client closed the connection (e.g closed browser, etc). It can happen. But this error was thrown and thrown a massive number of times and locked the app.

I repro'd locally by slamming my .NET app with a console app/stress tester, then closing the app, then starting the app again.

When i paused the debugger, i noted the app was stuck on this line:
![capture3](https://cloud.githubusercontent.com/assets/930343/12875764/21d291ac-ce45-11e5-924e-e59062cec457.PNG)

When i say "stuck", i mean either it's blocking on that line, or the error is being rethrown so much that it's always on that line. Is it trying to install a handler each time for that exception, then re-throwing error, then installing handler again etc?

I'm using BugSnag in my `OnError` Nancy handler (basically, a global error handler) like so:

```
var bugSnag = new BaseClient("myApiKey");
bugSnag.Notify("something");
```

So anytime an error is thrown in my app, i do the above.

So nothing new there. BugSnag reporting was working fine for around a year, only when i upgraded to OWIN/Katana did this problem surface.

If i take out my BugSnag reporting code, my app doesn't crash.

Can anyone shed some light on this? Do i need to create a singleton `BaseClient`? Or does the current implementation of this library simply not support OWIN/Katana?

Im on BugSnag v1.2.0.0.

Thanks.

**Comment by martin308** [comment]
@RPM1984 we have just pushed an alpha of version 2 of this notifier which should better support owin/katana. Let us know if you have any more feeback!

**Comment by RPM1984** [comment]
Thanks @martin308 ! I'll try and check it out in the future. Do you have an ETA on when a stable v2 will be released?

**Comment by martin308** [comment]
@RPM1984 it depends on the feedback that we get on the pre release but we are hoping for it to be very soon
