### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by jmshal** [bugsnag/bugsnag-dotnet#60]
Are there any plans to support .NET Core?

**Comment by martin308** [comment]
hey @jacobmarshall there are indeed plans to support .net core! We are working on a rewrite of the notifier which will target net35/net45/netstandard13, nothing to show yet but hopefully soon we can push up a work in progress PR

**Comment by jacobmarshall** [comment]
Awesome, thanks @martin308, much appreciated.

**Comment by piazera** [comment]
Any update on that subject?

**Comment by davidMuir** [comment]
Any updates at all on this would be good. We're going to be making a major move on .NET Core in a few months and Bugsnag is one of the few things holding us back at the moment.

**Comment by KoanLeeroy** [comment]
Ditto. Paying subscriber of Bugsnag and moved to .Net core on a new project that's about to go to GA. Really would like a notifier...

**Comment by yaakov-h** [comment]
Any update on this, @martin308? There really doesn't appear to be much going on in this project.

**Comment by JeremyNevill** [comment]
I'm in need of this one as well - .net core 2.0 target for my project.

**Comment by kattrali** [comment]
Hi all,

We are working on this. There hasn't been much moving on bugsnag-dotnet recently, as it has taken some time for us to rethink how we need to build notifier libraries to make them easier to change in the future. I'm hoping to have something ready for the end of the year, and possibly something to try sooner.

Our next goals for .NET are:

* Having separate dlls for the different types of .NET projects
* Reducing dependencies
* Supporting report modifications through callbacks 

Given these changes, we should soon be in a better position to add Core support and more. I'd like to know more about the types of apps people are building and the tools being used, and if anyone is happy to share, please reach out via this issue or via email (delisa@bugsnag). Thanks!

**Comment by yaakov-h** [comment]
@kattrali 

> Having separate dlls for the different types of .NET projects

Isn't this what .NET Standard is supposed to take care of? This sounds backwards to me.

**Comment by kattrali** [comment]
@yaakov-h Agreed! But I'd like to maintain support for folks using older versions without creating issues for anyone building newer standard projects.

**Comment by sgtfrankieboy** [comment]
Any updates on the .NET Core progression? It has been available for over a year, and its meant to replace the old ASP.Net stuff.

**Comment by gsaada** [comment]
Hey, Any update on .net standard support?
We are looking for a way to work with Buganag for .netstandard 1.3 SDK.

**Comment by martin308** [comment]
Hi all 👋, we have started working on this full time now. So far we have still been able to target the frameworks that I mentioned above (net35/net45/netstandard13). I will keep this thread up to date if that needs to change at any point. If you have any additional feedback or requests you can also reach me via email (martin@bugsnag.com). Thanks for you patience!

**Comment by martin308** [comment]
I have just pushed v2 (alpha) of our .net notifier which support ASP.NET Core to Nuget. It is an alpha release right now but we would love to have any feedback on it https://www.nuget.org/packages/Bugsnag.AspNet.Core

**Comment by mylaimani** [comment]
Hi is there any help document available to implement ASPNet.Core

**Comment by kendrome** [comment]
@mylaimani Looks like they have examples at https://github.com/bugsnag/bugsnag-dotnet/tree/v2/examples

**Comment by martin308** [comment]
@mylaimani we are working on our docs now, you can see a preview of them here https://deploy-preview-643--docs-bugsnag.netlify.com/platforms/dotnet/asp-net-core/

Note, this link will stop working once these docs changes are live

**Comment by martin308** [comment]
This is now live everyone, thanks for all your help and feedback 🎉
