### ISSUE TITLE
bugsnag not tracing unhandled exception for VSTO application.  

### ISSUE THREAD

**Issue by Kaushik1987** [bugsnag/bugsnag-dotnet#68]
### Expected behavior
*[Unhandled exception should be traced by bugsnag  & shown to dashboard ]*

### Observed behavior
*[Not making any track for Unhandled exception raised by VSTO application ]*

### Steps to reproduce
*[Create test application which is build using VSTO template under visual studio & throw some error.]*

### Version
package id="Bugsnag" version="1.0.0.0" targetFramework="net45"

**Comment by martin308** [comment]
@Kaushik1987 are you able to provide any more details on this? How are you setting up Bugsnag in your application? Can you provide a sample VSTO application with Bugsnag that reproduces this?

**Comment by martin308** [comment]
@Kaushik1987 going to close this until we get some more information on how to reproduce the behaviour
