### ISSUE TITLE
[.NET Core] All Errors are showing URL https://****.com/Home/Error

### ISSUE THREAD

**Issue by JoshuaSG** [bugsnag/bugsnag-dotnet#75]
### Expected behavior
Show the original URL where the error occured

### Observed behavior
Shows the error URL

### Version
2.0.12-alpha

Here is the Bugsnag Setup
`                services.AddBugsnag(config => {
                    config.ApiKey = _options.BugSnag.ApiKey;
                    config.NotifyReleaseStages = new[] { "production" };
                });`

And here is the code that sets the error URL
 `app.UseExceptionHandler("/Home/Error");`

**Comment by martin308** [comment]
@JoshuaSG thanks for the report! Working on a fix for this now

**Comment by martin308** [comment]
This has been pushed to nuget now in the latest alpha
