### ISSUE TITLE
Can't mutate event

### ISSUE THREAD

**Issue by btecu** [bugsnag/bugsnag-dotnet#83]
It used to be possible in 1.x to change severity, `addToTab` and so on in `BeforeNotify`.

How is this done in 2.x?

**Comment by martin308** [comment]
@btecu we are in the process of completing the documentation for this. It will be coming soon to our docs site https://docs.bugsnag.com/platforms/dotnet/

**Comment by btecu** [comment]
Can you give me a few hints meanwhile?

The git page has this example:
```
client.BeforeNotify((configuration, report) => {
	report.User = new Bugsnag.Payload.User() { Name = "Testy McTest" };
});
```

However, `BeforeNotify` only takes one argument and I'm not able to set anything on the `report`.

**Comment by martin308** [comment]
@btecu ah the readme has not been updated, I'm sorry about that! I'll get that updated, in the meantime here are is an example that change some properties:

```
client.BeforeNotify((report) => {
  // add a single key under the 'custom' tab in the dashboard
  report.Event.Metadata.Add("paying account", true);

  // add a new tab into the dashboard with 'account' as the name
  report.Event.Metadata.Add("account", new Dictionary<string, object> { { "paying", true } });

  report.Event.User = new Bugsnag.Payload.User {
    Id = "1",
    Name = "Testy McTest",
    Email = "support@bugsnag.com" };

  report.Event.Context = "billing";

  report.Event.GroupingHash = report.OriginalException.Message;
});
```
